// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// do_match_after
RObject do_match_after(IntegerVector lin, IntegerVector ltarg, IntegerVector nmatch);
RcppExport SEXP _lyxport_do_match_after(SEXP linSEXP, SEXP ltargSEXP, SEXP nmatchSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type lin(linSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ltarg(ltargSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nmatch(nmatchSEXP);
    rcpp_result_gen = Rcpp::wrap(do_match_after(lin, ltarg, nmatch));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lyxport_do_match_after", (DL_FUNC) &_lyxport_do_match_after, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_lyxport(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
