run_Cloaders_lyxport <- function() {
  Cloaders <- attr( sys.function(), 'Cloaders')
  for( iCloader in names( Cloaders)) {
    flypatch <- system.file( sprintf( 'R/Cloaders_%s.R', iCloader), package='lyxport')
    if( nzchar( flypatch)) { # empty string if not
      # use that instead of built-in, eg if debugging
      source( flypatch, local=asNamespace( 'lyxport'), echo=FALSE, verbose=FALSE)
    } else {
      eval( Cloaders[[ iCloader]], asNamespace( 'lyxport'))
    }
  }
}
attr( run_Cloaders_lyxport, 'Cloaders') <- list( NULL# ))
,lyxport = quote({
TRUE
# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

do_match_after <- function(lin, ltarg, nmatch) {
    .Call(`_lyxport_do_match_after`, lin, ltarg, nmatch)
}

})
)[-1]

