# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

do_match_after <- function(lin, ltarg, nmatch) {
    .Call(`_lyxport_do_match_after`, lin, ltarg, nmatch)
}

